#db
USERNAME: postgres
PASSWORD: 123
URL: jdbc:postgresql://localhost:5432/cleverbank
DRIVER: org.postgresql.Driver
SCHEMA: clever_bank

#flyway
MIGRATION_LOCATION: filesystem:src/main/resources/db/migration

ACCRUE_PERSENT: 1


#error-messages
INCORRECT_ACC_NUMBER: "Incorrect format of account number: %s"
INCORRECT_ACC_AMOUNT: "Incorrect amount(should be greater than 0): %s"