#db
username: postgres
password: 123
url: jdbc:postgresql://localhost:5432/cleverbank
driver: org.postgresql.Driver


#error-info
INCORRECT_ACC_NUMBER: "Incorrect format of account number: %s"
INCORRECT_ACC_AMOUNT: "Incorrect amount(should be greater than 0): %s"